export const questions = [
    ["What’s the square root of Tuesday?", "4", "Banana", "Fish", "42"],
    ["Why is green equal to 6?", "Because purple said so.", "Math", "Color theory", "The moon told me"],
    ["How many apples does a giraffe carry on a Wednesday?", "None, it’s a giraffe!", "7", "3", "42"],
    ["What is the atomic number of a unicorn?", "123", "3", "7", "42"],
    ["What does a cloud wear when it’s cold?", "A jacket made of wind.", "Socks", "A sweater", "Nothing, it’s a cloud"],
    ["How many jellybeans fit into the sun?", "None, it’s too hot.", "42", "100", "7"],
    ["Why is the ocean salty?", "Because it got too much sunburn.", "Because of fish", "Because of rain", "Because of mermaids"],
    ["What’s the favorite color of a paperclip?", "Silver", "Purple", "Red", "Invisible"],
    ["Why is 5 afraid of 6?", "Because 6 7 8.", "Because of 7", "Because of 4", "Because 6 is a bully"],
    ["What’s the meaning of life, the universe, and everything?", "42", "A pineapple", "Bananas", "Nothing"],
    ["How much does a shadow weigh?", "None, it's weightless.", "5 grams", "10 kilograms", "2 pounds"],
    ["Can you eat a rainbow?", "Only in your dreams.", "Yes, with frosting", "Yes, with pizza", "No, it’s a myth"],
    ["What is the speed of a thought?", "Faster than light.", "3 mph", "5 meters per second", "The same as a turtle"],
    ["What color is a mirror?", "Silver, but it reflects everything.", "Clear", "Blue", "Red"],
    ["Can you download a cup of coffee?", "Only if you have Wi-Fi and magic.", "Yes, with the right app", "Yes, it’s in the cloud", "No, it's just a joke"],
    ["How many pancakes fit in a black hole?", "As many as you want, it’s a black hole.", "None", "3", "42"],
    ["What’s the favorite thing to do for a pizza when it’s feeling happy?", "It gets saucy!", "It spins", "It sleeps", "It gets crispy"],
    ["Why did the bicycle fall over?", "It was two-tired.", "It lost its balance", "It wanted to sleep", "Because it was too fast"],
    ["Why is the sky blue?", "Because of the ocean’s reflection.", "Because of paint", "Because of the sun", "Because of clouds"],
    ["How much wood would a woodchuck chuck?", "As much wood as a woodchuck would chuck.", "42", "None", "All of it"],
    ["What sound does a unicorn make?", "A sparkle noise.", "Neigh", "Meow", "Roar"],
    ["Can a fish cry?", "Not unless it’s a very emotional fish.", "Yes, it’s underwater", "No, fish don’t have tears", "Yes, if it’s a robot fish"],
    ["How do you catch a cloud?", "With a net made of sunshine.", "With a fishing rod", "With your hands", "By waiting for rain"],
    ["Why did the clock break up with the calendar?", "Because it felt time was running out.", "Because of the date", "Because of the leap year", "Because of the seasons"],
    ["What does a turtle do in its free time?", "It plays slow-motion chess.", "It reads books", "It goes for walks", "It watches the clouds"],
    ["How many stars are in a cup of tea?", "None, unless you’re drinking stardust.", "1", "7", "42"],
    ["What’s the speed of a snail on a scooter?", "Quite fast, for a snail.", "1 mph", "3 mph", "Super slow"],
    ["What is the sound of one hand clapping?", "Silence.", "A slap", "A clap", "A whistle"],
    ["What does a cloud eat for breakfast?", "Mist and light.", "Cereal", "Rain", "Fog"],
    ["What happens when you mix a giraffe with a helicopter?", "You get a flying giraffe.", "A giraffe who can’t fly", "A giraffecopter", "A loud noise"],
    ["How much does a pizza weigh on Mars?", "Less, due to lower gravity.", "The same", "More", "It’s weightless"],
    ["What’s the square root of a marshmallow?", "A soft number.", "A hard square", "Zero", "A bouncy ball"],
    ["Can a cactus sing?", "Only if it's in a musical.", "Yes, in the desert", "No, they don’t have mouths", "Yes, but only in the winter"],
    ["How long is a unicorn's horn?", "Long enough to make rainbows.", "5 inches", "42 centimeters", "A foot"],
    ["Why do penguins not fly?", "Because they prefer swimming.", "Because they don’t have wings", "Because it’s too cold", "Because they are lazy"],
    ["What do you call a sleeping dinosaur?", "A dino-snore!", "A quiet rex", "A snoozer", "A fossil"],
    ["How much does the internet weigh?", "It weighs as much as a cloud.", "10 pounds", "2 tons", "5 kilograms"],
    ["What’s the best way to catch a rainbow?", "With a jar of sunshine.", "With a fishing pole", "With a butterfly net", "With your hands"],
    ["What’s the name of the dog that can dance?", "A boogie woof.", "A salsa dog", "A tap dancing terrier", "A waltzing hound"],
    ["What happens when you touch a cloud with a broom?", "You get a dust storm.", "You make rain", "You stir up thunder", "You brush off lightning"],
    ["How many clocks can a cat knock off a table?", "As many as it pleases.", "One", "Seven", "None, cats are perfect"],
    ["What’s the sound of a rubber duck in space?", "Quack echo.", "Squeaky silence", "A honk", "A cosmic chirp"],
    ["Why do fish never play basketball?", "Because they don’t have hands!", "They prefer soccer", "They can’t reach the hoop", "They play underwater volleyball"],
    ["What happens when you cross a snowman with a dog?", "A snowdog that barks!", "A frozen puppy", "A barking snowball", "An ice cream cone"],
    ["What color does a rainbow turn when it’s sad?", "Gray, but only on Tuesdays.", "Red", "Yellow", "It doesn’t change"],
    ["What’s a hamster’s favorite type of music?", "Pop and wheel-rock.", "Classical", "Jazz", "Techno"],
    ["What happens when you put a banana in a spaceship?", "It goes to the moon with a peel!", "It turns into a rocket", "It freezes", "It floats away"],
    ["How do you make a paper airplane fly faster?", "By whispering good luck to it.", "By adding wings", "By throwing harder", "By painting it blue"],
    ["Why did the ghost go to the party?", "To scare up some fun.", "Because it’s Halloween", "It was bored", "It wanted to float around"]
];
